import { z } from "zod";

/** Canonical public permission vocabulary shared by operational and control-plane contracts. */
export const Permission = z.enum([
  "account:read",
  "account:admin",
  "members:manage",
  "workspace:create",
  "billing:read",
  "billing:manage",
  "workspace:read",
  "workspace:admin",
  "sessions:create",
  "sessions:read",
  "sessions:control",
  "stream:view",
  "stream:control",
  "stream:acknowledge",
  "files:upload",
  "files:read",
  "files:write",
  "terminal:attach",
  "documents:manage",
  "documents:search",
  "scheduled_tasks:manage",
  "scheduled_tasks:run",
  "github:manage",
  "github:use",
  "api_keys:manage",
  /** Literal organization-key authority to configure workspace usage allowances. */
  "usage_allowances:manage",
  "connections:read",
  "connections:write",
  "capabilities:manage",
  /** @deprecated alias of variable-sets:manage */
  "environments:manage",
  /** @deprecated alias of variable-sets:use */
  "environments:use",
  "variable-sets:list",
  "variable-sets:read",
  "variable-sets:write",
  "variable-sets:manage",
  "variable-sets:attach",
  "variable-sets:use",
  "secrets:list",
  "secrets:read",
  "secrets:write",
  "mcp_servers:attach",
  "codemode:call",
  "goals:manage",
  "enrollments:read",
  "enrollments:manage",
  "rigs:use",
  "rigs:manage",
  "artifacts:read",
  "artifacts:publish",
]);
export type Permission = z.infer<typeof Permission>;
