//! End-to-end self-update flow tests.
//!
//! These drive the REAL `check_update` orchestrator against a local mock release
//! tree (`tests/fixtures/release/`) signed with a THROWAWAY test key (committed
//! `tests/fixtures/test-key.pub`), so they never touch the production release
//! secret. They prove the security-critical invariants:
//!
//!   * a validly-signed artifact is ACCEPTED, downloaded, verified, and the atomic
//!     swap installs it;
//!   * a TAMPERED artifact is REJECTED at the signature gate (never installed);
//!   * a TAMPERED manifest is REJECTED at the manifest-signature gate;
//!   * a wrong sha256 in the manifest is REJECTED at the checksum gate;
//!   * a failed boot health-gate ROLLS BACK to the prior binary (never bricks).
//!
//! The fixtures are regenerated by `tests/fixtures/regenerate.sh` (needs the
//! `minisign` binary); they are committed so CI needs no signing tool.

use std::fs;
use std::path::{Path, PathBuf};

use opengeni_agent_update::{
    check_update, check_update_manifest, finalize_update, parse_manifest, CheckOutcome, DirSource,
    ManifestCheckOutcome, UpdateConfig, UpdateError,
};

/// The test pubkey text (NOT the release key) the fixtures were signed with.
fn test_pubkey() -> String {
    fs::read_to_string(fixtures_dir().join("test-key.pub")).expect("read test-key.pub")
}

#[test]
fn app_target_never_falls_back_to_a_standalone_binary() {
    let release = staged_release();
    let source = DirSource::new(release.path());
    let mut cfg = config_for(release.path());
    cfg.target = "universal-apple-darwin-app".to_string();
    assert!(matches!(check_update_manifest(&source, &cfg),
        Err(UpdateError::NoArtifactForTarget(target)) if target == cfg.target));
}

#[test]
fn manifest_only_check_does_not_download_the_artifact() {
    let release = staged_release();
    let artifact = release.path().join("agent/stable/agent-v1.0.1");
    fs::remove_file(&artifact).expect("remove artifact");
    fs::remove_file(format!("{}.minisig", artifact.display())).expect("remove artifact signature");
    let source = DirSource::new(release.path());
    let cfg = config_for(release.path());

    match check_update_manifest(&source, &cfg).expect("manifest check") {
        ManifestCheckOutcome::Available(plan) => {
            assert_eq!(plan.version, "1.0.1");
            assert!(plan.expected_size() > 0);
        }
        ManifestCheckOutcome::UpToDate(reason) => panic!("expected update plan: {reason}"),
    }
}

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Copies the committed release tree into a writable temp dir so a test can tamper
/// with it without dirtying the fixtures. Returns the temp root.
fn staged_release() -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("tempdir");
    copy_tree(&fixtures_dir().join("release"), dir.path());
    dir
}

fn copy_tree(src: &Path, dst: &Path) {
    for entry in fs::read_dir(src).expect("read_dir") {
        let entry = entry.expect("entry");
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            fs::create_dir_all(&to).expect("mkdir");
            copy_tree(&from, &to);
        } else {
            fs::copy(&from, &to).expect("copy");
        }
    }
}

fn config_for(base: &Path) -> UpdateConfig {
    let mut cfg = UpdateConfig::new(
        format!("file://{}", base.display()),
        "stable",
        "agent-test-1",
        "1.0.0", // current version; the fixture promotes 1.0.1
    );
    cfg.target = "x86_64-unknown-linux-musl".to_string();
    cfg.pubkey = test_pubkey();
    cfg
}

#[test]
fn valid_update_is_accepted_and_swaps_in() {
    let release = staged_release();
    let source = DirSource::new(release.path());
    let cfg = config_for(release.path());

    let outcome = check_update(&source, &cfg).expect("check");
    let pending = match outcome {
        CheckOutcome::Available(p) => p,
        CheckOutcome::UpToDate(reason) => panic!("expected an update, got up-to-date: {reason}"),
    };
    assert_eq!(pending.version, "1.0.1");

    // Install to a temp "live binary" path and confirm the verified bytes landed.
    let bin_dir = tempfile::tempdir().expect("bin dir");
    let bin = bin_dir.path().join("opengeni-agent");
    fs::write(&bin, b"OLD-1.0.0").expect("seed old binary");
    let backup = pending.apply_to(&bin).expect("apply");

    let expected =
        fs::read(release.path().join("agent/stable/agent-v1.0.1")).expect("read fixture artifact");
    assert_eq!(
        fs::read(&bin).expect("read new"),
        expected,
        "verified artifact is live"
    );
    assert_eq!(
        fs::read(&backup).expect("read backup"),
        b"OLD-1.0.0",
        "old binary retained"
    );

    // A passing health gate PROMOTES (deletes the backup).
    finalize_update(&bin, Ok(())).expect("finalize");
    assert!(!backup.exists(), "backup removed after a healthy promote");
}

#[test]
fn tampered_artifact_is_rejected_at_the_signature_gate() {
    let release = staged_release();
    // Flip a byte in the artifact AFTER signing; refresh ONLY would still leave the
    // signature stale. We also fix the manifest sha256 to isolate the SIGNATURE
    // failure from the checksum failure.
    let artifact_path = release.path().join("agent/stable/agent-v1.0.1");
    let mut bytes = fs::read(&artifact_path).expect("read");
    bytes.extend_from_slice(b"TAMPERED");
    fs::write(&artifact_path, &bytes).expect("write tampered");

    // Re-point the manifest's sha256 to the tampered bytes (so we hit the sig gate,
    // not the checksum gate) and re-sign the manifest with the test key would need
    // the secret — instead we keep the original manifest + its valid sig and ALSO
    // adjust nothing: the artifact sig is now stale => signature gate fires first.
    let source = DirSource::new(release.path());
    let cfg = config_for(release.path());

    let err = check_update(&source, &cfg).expect_err("tampered artifact must be rejected");
    assert!(
        matches!(err, UpdateError::Signature(_)),
        "expected a signature rejection, got {err:?}"
    );
}

#[test]
fn tampered_manifest_is_rejected_at_the_manifest_signature_gate() {
    let release = staged_release();
    // Corrupt the manifest body; its committed signature no longer matches.
    let manifest_path = release.path().join("agent/stable/manifest.json");
    let mut body = fs::read(&manifest_path).expect("read");
    body.extend_from_slice(b"\n");
    fs::write(&manifest_path, &body).expect("write");

    let source = DirSource::new(release.path());
    let cfg = config_for(release.path());
    let err = check_update(&source, &cfg).expect_err("tampered manifest must be rejected");
    assert!(matches!(err, UpdateError::Signature(_)), "got {err:?}");
}

#[test]
fn wrong_checksum_in_manifest_would_reject_a_byte_substituted_artifact() {
    // The fixture manifest pins the real sha256. If we substitute the artifact with
    // DIFFERENT bytes signed by the SAME key (so the signature passes) but leave the
    // manifest's sha256 pinned to the original, the checksum gate must fire. We can't
    // re-sign here (no secret), so we assert the checksum primitive directly against
    // the manifest value to prove the gate is wired with the manifest's sha256.
    let release = staged_release();
    let manifest_bytes =
        fs::read(release.path().join("agent/stable/manifest.json")).expect("read manifest");
    let manifest = parse_manifest(&manifest_bytes).expect("parse");
    let pinned = &manifest.artifacts[0].sha256;
    let artifact =
        fs::read(release.path().join("agent/stable/agent-v1.0.1")).expect("read artifact");
    // The pinned sha matches the real artifact...
    assert!(opengeni_agent_update::verify_checksum(&artifact, pinned).is_ok());
    // ...and a single different byte makes it fail.
    let mut tampered = artifact.clone();
    tampered[0] ^= 0xff;
    assert!(matches!(
        opengeni_agent_update::verify_checksum(&tampered, pinned).unwrap_err(),
        UpdateError::Checksum { .. }
    ));
}

#[test]
fn failed_health_gate_rolls_back_to_the_prior_binary() {
    let release = staged_release();
    let source = DirSource::new(release.path());
    let cfg = config_for(release.path());

    let pending = match check_update(&source, &cfg).expect("check") {
        CheckOutcome::Available(p) => p,
        CheckOutcome::UpToDate(r) => panic!("expected update: {r}"),
    };

    let bin_dir = tempfile::tempdir().expect("bin dir");
    let bin = bin_dir.path().join("opengeni-agent");
    fs::write(&bin, b"GOOD-1.0.0").expect("seed");
    pending.apply_to(&bin).expect("apply");
    // The new binary is now live...
    assert_ne!(fs::read(&bin).expect("read"), b"GOOD-1.0.0");

    // ...but it fails the boot health gate => roll back to the known-good binary.
    let health = Err(UpdateError::HealthCheck("NATS ping failed".to_string()));
    let err = finalize_update(&bin, health).expect_err("finalize should surface the failure");
    assert!(matches!(err, UpdateError::HealthCheck(_)));
    assert_eq!(
        fs::read(&bin).expect("read"),
        b"GOOD-1.0.0",
        "the prior known-good binary is restored — never bricked"
    );
}

#[test]
fn an_older_or_equal_version_is_up_to_date_not_an_error() {
    let release = staged_release();
    let source = DirSource::new(release.path());
    let mut cfg = config_for(release.path());
    // Already running 1.0.1 (== the manifest version) => up-to-date, not an update.
    cfg.current_version = "1.0.1".to_string();
    match check_update(&source, &cfg).expect("check") {
        CheckOutcome::UpToDate(_) => {}
        CheckOutcome::Available(_) => panic!("running version should be up-to-date"),
    }
}

#[test]
fn explicit_same_version_opt_in_returns_the_signed_plan() {
    let release = staged_release();
    let source = DirSource::new(release.path());
    let mut cfg = config_for(release.path());
    cfg.current_version = "1.0.1".to_string();
    cfg.allow_same_version = true;

    match check_update_manifest(&source, &cfg).expect("manifest check") {
        ManifestCheckOutcome::Available(plan) => assert_eq!(plan.version, "1.0.1"),
        ManifestCheckOutcome::UpToDate(reason) => {
            panic!("explicit same-version repair must keep the signed plan: {reason}")
        }
    }
}
