// Pure parts of the native call config plugin (no Expo imports), so they are
// testable on their own: option defaults and the generated App Intent source.
const SWIFT_FILE = "OpenGeniCallIntents.swift";
const APP_NAME_TOKEN = "{app}";
const DEFAULTS = {
  title: "Start a call",
  description: "Start a voice call with your agent.",
  shortTitle: "Call",
  systemImage: "phone.fill",
  phrases: ["Call {app}", "Start a call with {app}", "Talk to {app}"],
  microphonePermission: "Talk to your agent on voice calls.",
};

function swiftString(value) {
  return JSON.stringify(String(value)).replace(/\\u([0-9a-fA-F]{4})/g, "\\u{$1}");
}

/** A phrase literal: `{app}` becomes the app-name interpolation Siri requires. */
function swiftPhrase(phrase) {
  const parts = String(phrase).split(APP_NAME_TOKEN);
  if (parts.length !== 2) {
    throw new Error(
      `@opengeni/react-native: every call phrase must contain ${APP_NAME_TOKEN} exactly once (got "${phrase}").`,
    );
  }
  const [before, after] = parts.map((part) => swiftString(part).slice(1, -1));
  return `"${before}\\(.applicationName)${after}"`;
}

function intentsSource(call) {
  const phrases = call.phrases.map(swiftPhrase).join(",\n        ");
  return `// Generated by the @opengeni/react-native config plugin. Do not edit.
import AppIntents
internal import OpenGeniCall

@available(iOS 16.0, *)
struct OpenGeniStartCallIntent: AppIntent {
  static let title: LocalizedStringResource = ${swiftString(call.title)}
  static let description = IntentDescription(${swiftString(call.description)})
  static let openAppWhenRun: Bool = true

  @MainActor
  func perform() async throws -> some IntentResult {
    OpenGeniCallLauncher.requestStart()
    return .result()
  }
}

@available(iOS 16.0, *)
struct OpenGeniCallShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: OpenGeniStartCallIntent(),
      phrases: [
        ${phrases}
      ],
      shortTitle: ${swiftString(call.shortTitle)},
      systemImageName: ${swiftString(call.systemImage)}
    )
  }
}
`;
}

function resolveOptions(props = {}) {
  const call = { ...DEFAULTS, ...(props.call ?? {}) };
  if (!Array.isArray(call.phrases) || call.phrases.length === 0) {
    throw new Error("@opengeni/react-native: call.phrases must list at least one phrase.");
  }
  call.phrases.forEach(swiftPhrase);
  return {
    call,
    alternativeAppNames: call.alternativeAppNames ?? [],
    microphonePermission: props.microphonePermission ?? DEFAULTS.microphonePermission,
    appIntents: call.appIntents !== false,
  };
}

module.exports = { SWIFT_FILE, intentsSource, resolveOptions };
