// Pure parts of the call control (no Expo imports): options and the generated
// WidgetKit extension that puts a "Call <agent>" control in Control Center, on
// the Lock Screen and on the Action button (iOS 18 and later).
//
// A control's button runs an App Intent. With `openAppWhenRun` the system opens
// the app and performs the intent there, so the extension declares an intent
// with the same type name as the app's generated one; the app's copy does the
// work (it hands the request to the same start path as Siri and Phone recents).
const CONTROL_TARGET = "OpenGeniCallControl";
const CONTROL_SWIFT_FILE = "OpenGeniCallControl.swift";
const CONTROL_INFO_PLIST = "OpenGeniCallControl-Info.plist";
const APP_NAME_TOKEN = "{app}";
const CONTROL_DEFAULTS = {
  title: "Call {app}",
  description: "Start a voice call with your agent.",
  systemImage: "phone.fill",
  bundleIdSuffix: "CallControl",
  deploymentTarget: "18.0",
};

function swiftString(value) {
  return JSON.stringify(String(value)).replace(/\\u([0-9a-fA-F]{4})/g, "\\u{$1}");
}

function xmlEscape(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * The control options, or null when the host has not asked for a control.
 * `call.control` is `true` or an object; anything else leaves it out, so adding
 * an extension target (and its signing) is always the host's choice.
 */
function resolveControl(call, appName) {
  const requested = call.control;
  if (requested !== true && (typeof requested !== "object" || requested === null)) return null;
  const control = { ...CONTROL_DEFAULTS, ...(requested === true ? {} : requested) };
  const name = String(appName ?? "").trim();
  if (control.title.includes(APP_NAME_TOKEN) && !name) {
    throw new Error(
      `@opengeni/react-native: call.control.title uses ${APP_NAME_TOKEN} but the app has no name.`,
    );
  }
  control.title = control.title.split(APP_NAME_TOKEN).join(name);
  if (!/^[A-Za-z0-9-]+$/.test(control.bundleIdSuffix)) {
    throw new Error(
      "@opengeni/react-native: call.control.bundleIdSuffix may only contain letters, digits and hyphens.",
    );
  }
  if (!/^\d+\.\d+$/.test(control.deploymentTarget) || Number(control.deploymentTarget) < 18) {
    throw new Error(
      "@opengeni/react-native: call.control.deploymentTarget must be iOS 18.0 or later (for example 18.0).",
    );
  }
  return control;
}

function controlSource(call, control, kind) {
  return `// Generated by the @opengeni/react-native config plugin. Do not edit.
import AppIntents
import SwiftUI
import WidgetKit

/// Same type name as the app's intent: the system opens the app and runs the
/// app's copy, which starts the call. This copy never runs.
struct OpenGeniStartCallIntent: AppIntent {
  static let title: LocalizedStringResource = ${swiftString(call.title)}
  static let description = IntentDescription(${swiftString(call.description)})
  static let openAppWhenRun: Bool = true

  func perform() async throws -> some IntentResult {
    return .result()
  }
}

struct OpenGeniCallControl: ControlWidget {
  var body: some ControlWidgetConfiguration {
    StaticControlConfiguration(kind: ${swiftString(kind)}) {
      ControlWidgetButton(action: OpenGeniStartCallIntent()) {
        Label(${swiftString(control.title)}, systemImage: ${swiftString(control.systemImage)})
      }
    }
    .displayName(${swiftString(control.title)})
    .description(${swiftString(control.description)})
  }
}

@main
struct OpenGeniCallControlBundle: WidgetBundle {
  var body: some Widget {
    OpenGeniCallControl()
  }
}
`;
}

function controlInfoPlist({ displayName, version, buildNumber }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>$(DEVELOPMENT_LANGUAGE)</string>
  <key>CFBundleDisplayName</key>
  <string>${xmlEscape(displayName)}</string>
  <key>CFBundleExecutable</key>
  <string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key>
  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key>
  <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
  <key>CFBundleShortVersionString</key>
  <string>${xmlEscape(version)}</string>
  <key>CFBundleVersion</key>
  <string>${xmlEscape(buildNumber)}</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key>
    <string>com.apple.widgetkit-extension</string>
  </dict>
</dict>
</plist>
`;
}

/** Build settings for the extension target, matching the app's signing team. */
function controlBuildSettings({ bundleIdentifier, control, developmentTeam, debug }) {
  const settings = {
    APPLICATION_EXTENSION_API_ONLY: "YES",
    CLANG_ENABLE_MODULES: "YES",
    CODE_SIGN_STYLE: "Automatic",
    CURRENT_PROJECT_VERSION: "1",
    GENERATE_INFOPLIST_FILE: "NO",
    INFOPLIST_FILE: `${CONTROL_TARGET}/${CONTROL_INFO_PLIST}`,
    IPHONEOS_DEPLOYMENT_TARGET: control.deploymentTarget,
    LD_RUNPATH_SEARCH_PATHS:
      '"$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"',
    PRODUCT_BUNDLE_IDENTIFIER: `"${bundleIdentifier}.${control.bundleIdSuffix}"`,
    PRODUCT_NAME: '"$(TARGET_NAME)"',
    SDKROOT: "iphoneos",
    SKIP_INSTALL: "YES",
    SWIFT_EMIT_LOC_STRINGS: "YES",
    SWIFT_OPTIMIZATION_LEVEL: debug ? '"-Onone"' : '"-O"',
    SWIFT_VERSION: "5.0",
    TARGETED_DEVICE_FAMILY: '"1,2"',
  };
  if (debug) settings.SWIFT_ACTIVE_COMPILATION_CONDITIONS = '"DEBUG $(inherited)"';
  if (developmentTeam) settings.DEVELOPMENT_TEAM = developmentTeam;
  return settings;
}

module.exports = {
  CONTROL_TARGET,
  CONTROL_SWIFT_FILE,
  CONTROL_INFO_PLIST,
  resolveControl,
  controlSource,
  controlInfoPlist,
  controlBuildSettings,
};
