interface Args {
  out: string | null;
}

interface Resources {
  requests: { cpu: string; memory: string };
  limits: { cpu: string; memory: string };
}

if (import.meta.main) {
  const args = parseArgs(process.argv.slice(2));
  const values = renderTemporalValues(process.env);

  if (args.out) {
    await Bun.write(args.out, values);
  } else {
    process.stdout.write(values);
  }
}

export function renderTemporalValues(env: Record<string, string | undefined>): string {
  const host = env.TEMPORAL_POSTGRES_HOST?.trim();
  const port = env.TEMPORAL_POSTGRES_PORT?.trim() || "5432";
  const connectAddr = env.TEMPORAL_POSTGRES_CONNECT_ADDR?.trim() || (host ? `${host}:${port}` : "");
  if (!connectAddr) {
    throw new Error("TEMPORAL_POSTGRES_HOST or TEMPORAL_POSTGRES_CONNECT_ADDR is required");
  }
  const user = env.TEMPORAL_POSTGRES_USER?.trim() || "opengeni";
  const secretName = env.TEMPORAL_POSTGRES_SECRET_NAME?.trim() || "opengeni-temporal-postgres";
  const secretKey = env.TEMPORAL_POSTGRES_SECRET_KEY?.trim() || "password";
  const defaultDatabase = env.TEMPORAL_POSTGRES_DEFAULT_DATABASE?.trim() || "temporal";
  const visibilityDatabase =
    env.TEMPORAL_POSTGRES_VISIBILITY_DATABASE?.trim() || "temporal_visibility";
  const createDatabase = booleanEnv(env, "TEMPORAL_POSTGRES_CREATE_DATABASE", true);
  const shards = positiveIntegerEnv(env, "TEMPORAL_NUM_HISTORY_SHARDS", "128");
  const historyCacheMaxBytes = positiveIntegerEnv(
    env,
    "TEMPORAL_HISTORY_CACHE_MAX_BYTES",
    "134217728",
  );
  const historyCacheTtl = durationEnv(env, "TEMPORAL_HISTORY_CACHE_TTL", "10m");
  const eventsCacheMaxBytes = positiveIntegerEnv(
    env,
    "TEMPORAL_EVENTS_CACHE_MAX_BYTES",
    "67108864",
  );
  const eventsCacheTtl = durationEnv(env, "TEMPORAL_EVENTS_CACHE_TTL", "10m");
  const historyGoMemoryLimit = goMemoryLimitEnv(env, "TEMPORAL_HISTORY_GOMEMLIMIT", "768MiB");
  const frontendResources = resourcesEnv(env, "FRONTEND", {
    requests: { cpu: "200m", memory: "256Mi" },
    limits: { cpu: "1", memory: "512Mi" },
  });
  const historyResources = resourcesEnv(env, "HISTORY", {
    requests: { cpu: "250m", memory: "768Mi" },
    limits: { cpu: "1", memory: "1280Mi" },
  });
  const matchingResources = resourcesEnv(env, "MATCHING", {
    requests: { cpu: "100m", memory: "256Mi" },
    limits: { cpu: "500m", memory: "512Mi" },
  });
  const workerResources = resourcesEnv(env, "WORKER", {
    requests: { cpu: "100m", memory: "128Mi" },
    limits: { cpu: "500m", memory: "512Mi" },
  });
  const serviceMonitorEnabled = booleanEnv(env, "TEMPORAL_SERVICE_MONITOR_ENABLED", false);
  const tlsEnabled = booleanEnv(env, "TEMPORAL_POSTGRES_TLS_ENABLED", false);
  const tlsCaFile = env.TEMPORAL_POSTGRES_TLS_CA_FILE?.trim();
  const tlsCaConfigMapName = env.TEMPORAL_POSTGRES_TLS_CA_CONFIG_MAP_NAME?.trim();
  const tlsCaConfigMapKey = env.TEMPORAL_POSTGRES_TLS_CA_CONFIG_MAP_KEY?.trim() || "ca.pem";
  const tlsCaMount =
    tlsCaFile && tlsCaConfigMapName
      ? renderCaMount("temporal-postgres-ca", tlsCaConfigMapName, tlsCaConfigMapKey, tlsCaFile)
      : "";
  const tlsYaml = tlsEnabled
    ? `\n            tls:\n              enabled: true${tlsCaFile ? `\n              caFile: ${yamlScalar(tlsCaFile)}` : ""}`
    : "";

  return `# Generated by scripts/deployment-temporal-values.ts. Do not commit generated copies.
server:
${tlsCaMount}  replicaCount: 1
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: ${yamlScalar(shards)}
      datastores:
        default:
          sql:
            createDatabase: ${yamlScalar(String(createDatabase))}
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: ${yamlScalar(defaultDatabase)}
            connectAddr: ${yamlScalar(connectAddr)}
            connectProtocol: tcp
            user: ${yamlScalar(user)}
            existingSecret: ${yamlScalar(secretName)}
            secretKey: ${yamlScalar(secretKey)}
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: 1h${tlsYaml}
        visibility:
          sql:
            createDatabase: ${yamlScalar(String(createDatabase))}
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: ${yamlScalar(visibilityDatabase)}
            connectAddr: ${yamlScalar(connectAddr)}
            connectProtocol: tcp
            user: ${yamlScalar(user)}
            existingSecret: ${yamlScalar(secretName)}
            secretKey: ${yamlScalar(secretKey)}
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: 1h${tlsYaml}
  dynamicConfig:
    history.cacheSizeBasedLimit:
      - value: true
        constraints: {}
    history.hostLevelCacheMaxSizeBytes:
      - value: ${yamlScalar(historyCacheMaxBytes)}
        constraints: {}
    history.cacheTTL:
      - value: ${yamlScalar(historyCacheTtl)}
        constraints: {}
    history.cacheBackgroundEvict:
      - value:
          Enabled: true
          LoopInterval: 1m
          MaxEntryPerCall: 4096
        constraints: {}
    # A single host-level event cache avoids multiplying a 512 KiB cache by
    # every acquired history shard. Events remain durable in PostgreSQL.
    history.enableHostLevelEventsCache:
      - value: true
        constraints: {}
    history.eventsHostLevelCacheMaxSizeBytes:
      - value: ${yamlScalar(eventsCacheMaxBytes)}
        constraints: {}
    history.eventsCacheTTL:
      - value: ${yamlScalar(eventsCacheTtl)}
        constraints: {}
  frontend:
${renderResources(frontendResources)}  history:
${renderResources(historyResources)}    additionalEnv:
      - name: GOMEMLIMIT
        value: ${yamlScalar(historyGoMemoryLimit)}
  matching:
${renderResources(matchingResources)}  worker:
${renderResources(workerResources)}  metrics:
    annotations:
      enabled: true
    serviceMonitor:
      enabled: ${yamlScalar(String(serviceMonitorEnabled))}
      interval: 30s
      additionalLabels:
        opengeni.ai/monitoring: enabled
      metricRelabelings:
        # Temporal emits the same 20-bucket latency histogram for hundreds of
        # label combinations. Sum/count preserve rates and mean latency while
        # the unused buckets account for most of its Prometheus footprint.
        - action: drop
          sourceLabels: [__name__]
          regex: ".*latency.*_bucket"

web:
  enabled: false

schema:
  useHelmHooks: true
  backoffLimit: 100
  ttlSecondsAfterFinished: 86400

admintools:
  # The schema hooks bring their own admin-tools image. Keeping an idle shell
  # deployment consumes memory without serving runtime traffic.
  enabled: false
${tlsCaMount}`;
}

function parseArgs(rawArgs: string[]): Args {
  const out: Args = { out: null };
  for (let index = 0; index < rawArgs.length; index += 1) {
    const value = rawArgs[index]!;
    if (value === "--out") {
      const next = rawArgs[index + 1];
      if (!next) {
        throw new Error("--out requires a value");
      }
      out.out = next;
      index += 1;
      continue;
    }
    if (value.startsWith("--out=")) {
      out.out = value.slice("--out=".length);
      continue;
    }
    throw new Error(`Unknown argument: ${value}`);
  }
  return out;
}

function positiveIntegerEnv(
  env: Record<string, string | undefined>,
  name: string,
  fallback: string,
): string {
  const value = env[name]?.trim() || fallback;
  if (!/^[1-9][0-9]*$/.test(value)) {
    throw new Error(`${name} must be a positive integer`);
  }
  return value;
}

function booleanEnv(
  env: Record<string, string | undefined>,
  name: string,
  fallback: boolean,
): boolean {
  const raw = env[name]?.trim();
  if (!raw) return fallback;
  if (/^(1|true|yes)$/i.test(raw)) return true;
  if (/^(0|false|no)$/i.test(raw)) return false;
  throw new Error(`${name} must be true or false`);
}

function durationEnv(
  env: Record<string, string | undefined>,
  name: string,
  fallback: string,
): string {
  const value = env[name]?.trim() || fallback;
  if (!/^[1-9][0-9]*(?:ms|s|m|h)$/.test(value)) {
    throw new Error(`${name} must be a positive duration such as 10m`);
  }
  return value;
}

function goMemoryLimitEnv(
  env: Record<string, string | undefined>,
  name: string,
  fallback: string,
): string {
  const value = env[name]?.trim() || fallback;
  if (!/^[1-9][0-9]*(?:B|KiB|MiB|GiB|KB|MB|GB)$/.test(value)) {
    throw new Error(`${name} must be a positive Go memory limit such as 1152MiB`);
  }
  return value;
}

function kubernetesQuantityEnv(
  env: Record<string, string | undefined>,
  name: string,
  fallback: string,
): string {
  const value = env[name]?.trim() || fallback;
  if (!/^[1-9][0-9]*(?:Ki|Mi|Gi|k|M|G)$/.test(value)) {
    throw new Error(`${name} must be a positive Kubernetes memory quantity such as 512Mi`);
  }
  return value;
}

function cpuQuantityEnv(
  env: Record<string, string | undefined>,
  name: string,
  fallback: string,
): string {
  const value = env[name]?.trim() || fallback;
  if (
    !/^(?:[1-9][0-9]*m|(?:0|[1-9][0-9]*)(?:\.[0-9]{1,3})?)$/.test(value) ||
    cpuMilliUnits(value) === 0n
  ) {
    throw new Error(
      `${name} must be a positive Kubernetes CPU quantity such as 500m or 1, with at most three decimal places`,
    );
  }
  return value;
}

function cpuMilliUnits(value: string): bigint {
  if (value.endsWith("m")) return BigInt(value.slice(0, -1));
  const [cores, fraction = ""] = value.split(".");
  return BigInt(cores!) * 1000n + BigInt(fraction.padEnd(3, "0"));
}

function memoryBytes(value: string): bigint {
  const units: Record<string, bigint> = {
    Ki: 1024n,
    Mi: 1024n ** 2n,
    Gi: 1024n ** 3n,
    k: 1000n,
    M: 1000n ** 2n,
    G: 1000n ** 3n,
  };
  // Callers validate the quantity before comparing it, so every capture/unit exists.
  const match = /^([1-9][0-9]*)(Ki|Mi|Gi|k|M|G)$/.exec(value)!;
  const amount = match[1]!;
  const unit = match[2]!;
  return BigInt(amount) * units[unit]!;
}

function resourcesEnv(
  env: Record<string, string | undefined>,
  role: "FRONTEND" | "HISTORY" | "MATCHING" | "WORKER",
  defaults: Resources,
): Resources {
  // TEMPORAL_<ROLE>_{CPU,MEMORY}_{REQUEST,LIMIT}; history memory names stay compatible.
  const prefix = `TEMPORAL_${role}`;
  const resources = {
    requests: {
      cpu: cpuQuantityEnv(env, `${prefix}_CPU_REQUEST`, defaults.requests.cpu),
      memory: kubernetesQuantityEnv(env, `${prefix}_MEMORY_REQUEST`, defaults.requests.memory),
    },
    limits: {
      cpu: cpuQuantityEnv(env, `${prefix}_CPU_LIMIT`, defaults.limits.cpu),
      memory: kubernetesQuantityEnv(env, `${prefix}_MEMORY_LIMIT`, defaults.limits.memory),
    },
  };
  if (cpuMilliUnits(resources.requests.cpu) > cpuMilliUnits(resources.limits.cpu)) {
    throw new Error(`${prefix}_CPU_REQUEST must not exceed ${prefix}_CPU_LIMIT`);
  }
  if (memoryBytes(resources.requests.memory) > memoryBytes(resources.limits.memory)) {
    throw new Error(`${prefix}_MEMORY_REQUEST must not exceed ${prefix}_MEMORY_LIMIT`);
  }
  return resources;
}

function renderResources(resources: Resources): string {
  return `    resources:
      requests:
        cpu: ${JSON.stringify(resources.requests.cpu)}
        memory: ${yamlScalar(resources.requests.memory)}
      limits:
        cpu: ${JSON.stringify(resources.limits.cpu)}
        memory: ${yamlScalar(resources.limits.memory)}
`;
}

function renderCaMount(
  volumeName: string,
  configMapName: string,
  configMapKey: string,
  mountPath: string,
): string {
  return `  additionalVolumes:
    - name: ${yamlScalar(volumeName)}
      configMap:
        name: ${yamlScalar(configMapName)}
        items:
          - key: ${yamlScalar(configMapKey)}
            path: ca.pem
  additionalVolumeMounts:
    - name: ${yamlScalar(volumeName)}
      mountPath: ${yamlScalar(mountPath)}
      subPath: ca.pem
      readOnly: true
`;
}

function yamlScalar(value: string): string {
  if (/^(true|false|[0-9]+)$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}
