import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

/*
 * The API's self-contained GitHub browser pages (apps/api/src/routes/
 * github-browser-pages.ts) must render in the web app's typefaces on machines
 * that do not have them installed. The fonts are inlined as data: URIs from the
 * exact files the web app ships (apps/web's @fontsource-variable packages,
 * latin subset), so the pages need no font route, asset copy step or bundler
 * loader in any of the API's distributions (Bun source, Bun.build bundle, tsup).
 */

const repoRoot = resolve(import.meta.dir, "..");
const fontsourceRoot = resolve(repoRoot, "apps/web/node_modules/@fontsource-variable");
export const githubPageFontsOutputPath = resolve(
  repoRoot,
  "apps/api/src/routes/github-browser-fonts.gen.ts",
);

const FONTS = [
  {
    family: "Inter Variable",
    file: "inter/files/inter-latin-wght-normal.woff2",
    weight: "100 900",
  },
  {
    family: "DM Sans Variable",
    file: "dm-sans/files/dm-sans-latin-wght-normal.woff2",
    weight: "100 1000",
  },
] as const;

// fontsource's latin unicode-range, identical for both families.
const LATIN_RANGE =
  "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD";

export async function renderGitHubPageFontsModule(): Promise<string> {
  const faces: string[] = [];
  for (const font of FONTS) {
    const css = await readFile(
      resolve(fontsourceRoot, font.file.split("/")[0]!, "wght.css"),
      "utf8",
    );
    if (!css.includes(LATIN_RANGE) || !css.includes(`font-weight: ${font.weight};`)) {
      throw new Error(`${font.family}: fontsource latin face changed; update ${import.meta.path}`);
    }
    // Hex, not base64: a hex run has no word boundaries, so committed font bytes
    // cannot read as words to the public-repository hygiene scan.
    const hex = (await readFile(resolve(fontsourceRoot, font.file))).toString("hex");
    faces.push(
      `  { family: ${JSON.stringify(font.family)}, weight: ${JSON.stringify(font.weight)}, woff2Hex: ${JSON.stringify(hex)} },`,
    );
  }
  return `/* This file is generated by scripts/generate-github-page-fonts.ts. Do not edit. */
/* Inter and DM Sans (SIL Open Font License 1.1), latin subset, from apps/web's @fontsource-variable packages. */
const LATIN_RANGE = ${JSON.stringify(LATIN_RANGE)};
const FONTS = [
${faces.join("\n")}
];
/** \`@font-face\` rules for the fonts above, embedded as data: URIs. */
export const GITHUB_PAGE_FONT_FACES = FONTS.map(
  ({ family, weight, woff2Hex }) =>
    \`@font-face{font-family:"\${family}";font-style:normal;font-display:swap;font-weight:\${weight};src:url(data:font/woff2;base64,\${Buffer.from(woff2Hex, "hex").toString("base64")}) format("woff2-variations");unicode-range:\${LATIN_RANGE}}\`,
).join("");
`;
}

if (import.meta.main) {
  const source = await renderGitHubPageFontsModule();
  if (process.argv.includes("--check")) {
    const current = await readFile(githubPageFontsOutputPath, "utf8").catch(() => "");
    if (current !== source) {
      throw new Error(
        "generated GitHub page fonts are stale; run bun scripts/generate-github-page-fonts.ts",
      );
    }
    console.log(`verified ${githubPageFontsOutputPath}`);
  } else {
    await writeFile(githubPageFontsOutputPath, source);
    console.log(`generated ${githubPageFontsOutputPath}`);
  }
}
