// Generates the native design tokens from the web stylesheet, so the native renderer uses
// exactly the colors, radii and type scale the web app computes (including oklch values,
// which React Native cannot parse). Run against a dev web server:
//   bun scripts/generate-native-tokens.ts http://127.0.0.1:3000/dev/session-timeline
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { chromium } from "playwright";

const url = process.argv[2] ?? "http://127.0.0.1:3000/dev/session-timeline";
const out = join(import.meta.dir, "../packages/react-native/src/ui/web-tokens.gen.ts");

async function resolveScheme(scheme: "light" | "dark") {
  const browser = await chromium.launch();
  const page = await browser.newPage({ colorScheme: scheme });
  await page.goto(`${url}?bare=1`, { waitUntil: "networkidle" });
  const tokens = await page.evaluate(() => {
    const root = getComputedStyle(document.documentElement);
    const names = new Set<string>();
    for (const sheet of Array.from(document.styleSheets)) {
      let rules: CSSRuleList;
      try {
        rules = sheet.cssRules;
      } catch {
        continue;
      }
      const visit = (list: CSSRuleList) => {
        for (const rule of Array.from(list)) {
          if ("style" in rule) {
            const style = (rule as CSSStyleRule).style;
            for (let index = 0; index < style.length; index += 1) {
              const name = style.item(index);
              if (name.startsWith("--og-")) names.add(name);
            }
          }
          if ("cssRules" in rule) visit((rule as CSSGroupingRule).cssRules);
        }
      };
      visit(rules);
    }
    const probe = document.createElement("div");
    document.body.appendChild(probe);
    const colors: Record<string, string> = {};
    const lengths: Record<string, string> = {};
    for (const name of Array.from(names).sort()) {
      const raw = root.getPropertyValue(name).trim();
      if (!raw) continue;
      if (name.startsWith("--og-color-")) {
        probe.style.color = "";
        probe.style.color = `var(${name})`;
        const resolved = getComputedStyle(probe).color;
        // Normalize any color space to sRGB via canvas.
        const canvas = document.createElement("canvas");
        canvas.width = canvas.height = 1;
        const context = canvas.getContext("2d")!;
        context.fillStyle = resolved;
        context.fillRect(0, 0, 1, 1);
        const [r, g, b, a] = context.getImageData(0, 0, 1, 1).data;
        colors[name.slice("--og-color-".length)] =
          a === 255 ? `rgb(${r}, ${g}, ${b})` : `rgba(${r}, ${g}, ${b}, ${(a / 255).toFixed(3)})`;
      } else if (/^--og-(radius|font-size|space)-/.test(name) && /^-?[\d.]+px$/.test(raw)) {
        lengths[name.slice(5)] = raw;
      }
    }
    probe.remove();
    return { colors, lengths };
  });
  await browser.close();
  return tokens;
}

const light = await resolveScheme("light");
const dark = await resolveScheme("dark");
const px = (value: string) => Number.parseFloat(value);
const lengths = Object.fromEntries(
  Object.entries(light.lengths).map(([key, value]) => [key, px(value)]),
);
const source = `// GENERATED by scripts/generate-native-tokens.ts from the web stylesheet. Do not edit.
// Regenerate after changing packages/react/styles/tokens.css.
export const webColorsLight = ${JSON.stringify(light.colors, null, 2)} as const;

export const webColorsDark = ${JSON.stringify(dark.colors, null, 2)} as const;

export const webLengths = ${JSON.stringify(lengths, null, 2)} as const;
`;
await writeFile(out, source);
console.log(
  `wrote ${out}: ${Object.keys(light.colors).length} colors, ${Object.keys(lengths).length} lengths`,
);
