//! Generated wire-protocol types for the Opengeni self-hosted agent.
//!
//! This crate is the **Rust side** of the single-source-of-truth wire protocol
//! defined once in [`agent/proto/opengeni_agent.proto`]. The build script
//! ([`build.rs`]) compiles that schema into Rust types via `prost`; the same
//! schema is code-generated to TypeScript for the control plane (see
//! `packages/agent-proto`). Because both stacks are generated from the one IDL,
//! the control plane and the agent can never drift — the guarantee M0 exists to
//! establish, proven by a cross-stack round-trip test.
//!
//! # Layout
//!
//! All generated messages and enums live in the [`v1`] module, mirroring the
//! proto package `opengeni.agent.v1`. Encode/decode is via the [`prost::Message`]
//! trait, re-exported here as [`Message`] for convenience.
//!
//! ```no_run
//! use opengeni_agent_proto::{v1, Message};
//!
//! let ping = v1::PingRequest { nonce: 42 };
//! let bytes = ping.encode_to_vec();
//! let decoded = v1::PingRequest::decode(bytes.as_slice()).unwrap();
//! assert_eq!(ping.nonce, decoded.nonce);
//! ```

#![doc(html_root_url = "https://docs.rs/opengeni-agent-proto")]

/// The `opengeni.agent.v1` wire-protocol types, generated from the proto IDL.
pub mod v1 {
    #![allow(missing_docs, clippy::pedantic, clippy::all)]
    //! Generated by `prost` from `agent/proto/opengeni_agent.proto`. Do not edit;
    //! regenerate via `agent/scripts/codegen.sh`.
    include!(concat!(env!("OUT_DIR"), "/opengeni.agent.v1.rs"));
}

/// The `prost` message trait, re-exported so callers can encode/decode without a
/// direct `prost` dependency.
pub use prost::Message;

/// The canonical cross-stack test corpus, kept in lock-step with the TypeScript
/// corpus, used by the round-trip test to prove the two generated stacks agree.
///
/// Compiled under `cargo test` and behind the `test-corpus` feature (so the
/// fixture-generator binary can build it) — never in a default production build.
#[cfg(any(test, feature = "test-corpus"))]
pub mod corpus;
